# -*- coding: utf-8 -*-
"""Lapwork1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xettHEi5WDeM9bL_4-qtNxpKmVkBftKm
"""

#Problem 1 - Caculate circle area
radius = float(input("Enter circle radius? "))
area = 3.14 * radius ** 2
print("Circle area =", area)

#Problem 2 - converst C into F
celsius = float(input("Enter the temperature in Celsius?"))
fahrenheit = celsius * 9/5 + 32
print(f"{celsius} (C) = {fahrenheit} (F)") #f-string
#print("{} (C) = {} (F)".format(celsius, fahrenheit))
#print(celsius, "(C) = ", fahrenheit, "(F)")

#Problem 3 - prime number
num = int(input("Enter a number? "))
is_prime = True
if num < 2:
    is_prime = False
else:
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

if is_prime:
    print(num, "is a prime number")
else:
    print(num, "is a NOT prime number")

#Problem 4 - perfect number
num = int(input("Enter a number?"))
sum_divisors = 0

for i in range(1, num):
    if num % i == 0:
        sum_divisors = sum_divisors + i

if sum_divisors == num:
    print(num, "is a perfect number")
else:
    print(num, "is a NOT perfect number")

#Problem 5 - favorite color
colors = ["Yellow", "Blue", "Black", "Red", "White"]

favorite = input("What is your favorite color? ")

if favorite in colors:
    index = colors.index(favorite)
    print("Your color is at index", index, "in my list")
else:
    print("Sorry, I could not find your color")

#Problem 6 - range(start, end, step)
range1 = range(0, 7)
print("range1:", list(range1))

range2 = range(1, 11, 3)
print("range2:", list(range2))

range3 = range(5, 0, -1)
print("range3:", list(range3))

range4 = range(6, -3, -2)
print("range4:", list(range4))

#Problem 7 - remove dollar
def remove_dollar_sign(s):
    new_string = s.replace("$", "")
    return new_string

print(remove_dollar_sign("$100"))              # 100
print(remove_dollar_sign("The price is $50"))  # The price is 50
print(remove_dollar_sign("$5 and $10"))        # 5 and 10
print(remove_dollar_sign("No dollar here"))    # No dollar here

#Problem 8 - even number
def extract_even(l):
    result = []
    for num in l:
        if num % 2 == 0:
            result.append(num)
    return result

l = [1, 4, 5, -1, 10]
print(extract_even(l))

#Problem 9 - factorial
def calculate_factorial(n):
    result = 1
    for i in range(1, n + 1):
        result = result * i
    return result

num = int(input("Enter number? "))
print(calculate_factorial(num))

#Problem 10 - divisor

def get_divisors(n):
    divisors = []
    for i in range(1, n + 1):
        if n % i == 0:
            divisors.append(i)
    return divisors

num = int(input("Enter number? "))
print(get_divisors(num))

#Problem 11 - compute distance

#p1 = (x1, y1)
x1 = float(input("Enter x1? "))
y1 = float(input("Enter y1? "))

#p2 = (x2, y2)
x2 = float(input("Enter x2? "))
y2 = float(input("Enter y2? "))

d = ((x1 - x2)**2 + (y1 - y2)**2)**0.5
print("Distance: ", d)

from ast import pattern
#Problem 12 - print pattern

def print_pattern(m, n):
    for row in range(m):
        for column in range(n):
            if row == 0 or row == m - 1 or column == 0 or column == n - 1:
                print("*", end=" ")
            else:
                print(" ", end=" ")
        print()

print_pattern(4,5)