# -*- coding: utf-8 -*-
"""Lapwork1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1s1GCzFEhs_MPVo2iT7b6Ez0aFfdZWy
"""

def input_students():
    students = []
    n = int(input("Number of students: "))
    for i in range(n):
        sid = input("Student id: ")
        name = input("Name: ")
        dob = input("Date of birth: ")
        students.append({"id": sid, "name": name, "dob": dob})
    return students


def input_courses():
    courses = []
    n = int(input("Number of courses: "))
    for i in range(n):
        cid = input("Course id: ")
        name = input("Course name: ")
        courses.append({"id": cid, "name": name})
    return courses


def find_course(courses, cid):
    for c in courses:
        if c["id"] == cid:
            return c
    return None


def find_student(students, sid):
    for s in students:
        if s["id"] == sid:
            return s
    return None


def input_marks(students, courses, marks):
    list_courses(courses)
    cid = input("Select course id: ")
    course = find_course(courses, cid)
    if not course:
        print("Course not found!")
        return
    marks.setdefault(cid, {})
    for s in students:
        mark = float(input(f"Mark for {s['name']}: "))
        marks[cid][s["id"]] = mark


def list_courses(courses):
    for c in courses:
        print(c["id"], "-", c["name"])


def list_students(students):
    for s in students:
        print(s["id"], "-", s["name"], "-", s["dob"])


def show_marks(students, courses, marks):
    list_courses(courses)
    cid = input("Select course id: ")
    if cid not in marks:
        print("No marks for this course!")
        return
    for sid, mark in marks[cid].items():
        s = find_student(students, sid)
        print(sid, "-", s["name"] if s else "?", ":", mark)


def main():
    students, courses, marks = [], [], {}
    while True:
        print("\n1.Students 2.Courses 3.Input marks 4.List courses 5.List students 6.Show marks 0.Exit")
        c = input("Choose: ")
        if c == "1":
            students = input_students()
        elif c == "2":
            courses = input_courses()
        elif c == "3":
            input_marks(students, courses, marks)
        elif c == "4":
            list_courses(courses)
        elif c == "5":
            list_students(students)
        elif c == "6":
            show_marks(students, courses, marks)
        elif c == "0":
            break


if __name__ == "__main__":
    main()